version: '3'

services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: influence-mobile
    ports:
      - "3000:3000"
    volumes:
     - .:/app
    depends_on:
      - db
    container_name: influence-mobile-app
  db:
    image: postgres:16.1
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: influence_mobile_development
    container_name: influence-mobile-db

volumes:
  pg_data:
